title: Datadrivet Infrastructure Documentation
description: Documentation for Datadrivet infrastructure setup and services
baseurl: ""
url: "https://knowit-solutions-cocreate.github.io"

markdown: kramdown
highlighter: rouge
theme: minimal-mistakes-jekyll

# GitHub Pages source directory
source: .

include: ["_pages"]

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
  # _pages
  - scope:
      path: ""
      type: pages
    values:
      layout: single

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - jemoji
  - jekyll-include-cache 

exclude:
  - devenv.lock
  - devenv.nix
  - devenv.yaml
  - README.md
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor